novnc/noVNC

include/rfb.js
include/websock.js
tests/test.rfb.js

Prevents possible memory and event notification leaks when tearing down
connection and reestablishing a new one.

Unregister event listeners from websock.

---

debian/novnc.install

It's used but not being packaged.  Let's fix that!

keysym.js needs inclusion in debian's install list

---

include/display.js
include/rfb.js
include/ui.js
tests/test.display.js
tests/test.rfb.js
tests/viewport.html
vnc.html
vnc_auto.html

Cleaned up version of #271 
This feature is divided into 4 commits:
1: display.js
2: rfb.js
3: ui.js, vnc.html & vnc_auto.html
4: tests

Support ExtendedDesktopSize and SetDesktopSize

---

include/util.js

The [`getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element.getBoundingClientRect) call is native JavaScript and supported since Chrome 1, Firefox 3, Safari 4, IE4 (excluding width and height, which are not used here). It works more consistently than the existing implementation, especially when working with position static and fixed element hierarchies.
All tests still pass (although there are no tests covering this function). We did manually test in our own application with these changes, as well as in the packaged `vnc.html`.

Replace custom getPosition algorithms with getBoundingClientRect.

---

include/rfb.js
include/ui.js

Commit 155d78b39933a396d2555376f4e70f976c30b86d prevented reconnections
from working properly.  This fixes that by creating a new RFB object
after disconnecting or failing.
Furthermore, this ensures that a new connection cannot be opened util
we've actually disconnected (either by timer or by receiving a `close`
event).
Closes #452

Fix disconnect/reconnect issues

---

include/util.js

Commit 5108c4635c847de9be0edadf572f7426f351b66a caused a regression
in the case where scrolling is used -- getPosition return position
relative to the viewport, while getEventPosition expected a position
relative to the page.
As per
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect,
the fix for this is simply to add the `pageXOffset` and `pageYOffset` to
the output of `getBoundingClientRect()`.
Fixes #459.

Make Util.getPosition be relative to page

---

include/base.css
include/display.js
include/rfb.js
include/ui.js
tests/test.display.js
tests/test.rfb.js
vnc.html

This fixes issues #446 and #463 by using a different approach of getting the full size of the canvas. Instead of using window.innerWidth and window.innerHeight this would resize the canvas to fit the noVNC_container which covers the entire page.
Edit: This also fixes issue #465

Fix resize in Firefox on Android

---

utils/launch.sh

Previously, in launch.sh, `$HERE` was the directory of `$0`.
However, if `$0` was actually a symlink, `$HERE` would be
wherever the symlink was, which could cause issues (for
example, the script wouldn't be able to local `$WEB` or
`$WEBSOCKIFY` properly).
Now, `$HERE` looks at whatever `$0` points at instead.
Closes #447.

Follow symbolic links in launch.sh

---

include/display.js
include/rfb.js
include/ui.js
include/util.js
tests/test.display.js
vnc.html
vnc_auto.html

Throw error from constructor on Display error
Previously, if an error was thrown from the Display constructor in the RFB constructor, we would attempt to use `RFB#updateState`` to handle this.  However, `RFB#updateState` attempts to close the WebSocket connection, which doesn't exist at this point.
In the constructor, it's probably just better to raise an exception instead (making sure to clean up anything relevant), both for errors from the display constructor, and for errors due to WebSocket emulation.
Fixes #460

Throw exceptions from RFB constructor

---

package.json

So people can follow the 'unit tests' instructions, we need
to make sure PATH includes the karma bin directory otherwise
we see the following:
```
aclouter@stevemcqueen:/usr/src/aten-ikvm/noVNC$ npm test
> noVNC@0.5.0 test /usr/src/aten-ikvm/noVNC
> karma start karma.conf.js
sh: 1: karma: not found
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

slip in PATH for 'npm test' as not everyone has karma

---

include/base.css
include/ui.js
vnc.html

This pull request simply moves the style and onsubmit declarations from #keyboardinput in vnc.html to base.css and ui.js, making it possible to use noVNC on mobile devices with an active Content Security Policy after these small changes.
An example policy header working with noVNC (note ws://127.0.0.1:8080 needs to be replaced with the scheme, host & port noVNC should connect to):
```
default-src 'none'; font-src 'self'; script-src 'self'; img-src 'self' data:; style-src 'self'; connect-src 'self' ws://127.0.0.1:8080;
```
I admit this is not terribly useful if noVNC should connect to different clients, but for integration into specific applications this may improve security, and the needed changes are not too big.

Make noVNC compatible with Content Security Policies

---

include/rfb.js
include/websock.js

For performance reasons, the `handle_tight` function skips the
use of the receive queue API and uses the raw receive queue directly.
Because of the way that typed array receive queue gets reused, this
introduced the potential for buffer over-reads.
To address this, a new function, `rQwhole`, was introduced.
`rQwhole` simply returns a new view into the receive queue that
starts at 0 and ends at the current recorded end of the queue.
`handle_tight` now makes use of this function.
Fixes #522

Fix buffer over-reads in handle_tight

---

docs/notes
include/inflator.js
include/rfb.js
utils/inflator.partial.js

Previously, we used a fixed chunkSize of 100KiB for Pako's output
buffer.  Using a hardcoded size caused issues, since Pako would assume
we wanted to use multiple chunks, and we didn't deal with this.  Now,
`Inflator#inflate()` takes a new `expected` argument, which indicates
the expected output size.  If this is bigger than the current chunkSize,
Inflator allocates a new output buffer that's big enough to hold the
output.
Fixes #531

Make sure Pako always has enough room

---

include/rfb.js

Should return and wait for the sendPassword-call to trigger the actual authentication. Fixes #542.

Fixes VNC standard auth using onPasswordRequired callback

---

include/websock.js
tests/test.websock.js

This PR causes the receive queue to be resized in order to fit incoming messages.  There is a hard cap of a size of 40 MiB, so that we can't consume too much memory by accident.
Fixes #557

Resize Receive Queue to Fit Incoming Messages

---

include/ui.js
include/webutil.js
vnc.html
vnc_auto.html

Any config variable like host, port, password, token may be
specified either in the query string (like now), or in the URL hash
fragment. In case a given variable is present in both, the value in the
fragment takes precedence. Supplying variables in the fragment avoids
leaking them to the web server hosting the noVNC viewer HTML.

Add hash fragment as an optional method to supply config variables.

---

include/display.js

This commit ensures that input arrays are copied to new storage when
they are pushed onto the render queue.  This ensures that they are
not overwritten before they are eventually used.
Fixes #571

Make sure to copy arrays when using render queue

---

include/webutil.js

IE11 with compat mode turned off has been observed displaying this behavior.  This commit checks for and corrects this broken behavior.
Fixes #591

Handle missing leading slash in elem.pathname

---

include/rfb.js

We wait until the mouse button is released to determine whether a mouse event is a tap or drag, and make that determination by tracking whether the viewport has actually moved.
This makes for a better experience on mobile, I think.  So much so that for my use, I'm starting mobile users in viewport dragging mode by default.
--Jonathan Bennett

Adds tap-to-click in viewport drag mode

---

include/rfb.js
include/ui.js
tests/test.rfb.js
vnc_auto.html

In order to follow the surrounding coding-standards, the setDesktopSize client message is now split from the public function which now is called requestDesktopSize.

Split the setDesktopSize function

---

include/display.js
include/rfb.js

This PR fixes the ImageData constructor support detection, and reverts a workaround to a Firefox nightly bug which snuck in as part of a different commit.

Misc Fixes (ImageData Constructor Detection and Firefox Nightly Bug Workaround)

---

utils/launch.sh

Added an option. `--ssl-only`, to the `launch.sh` script.  This option is passed through to the underlying `websockify` executable.  The end result is a `noVNC` session which rejects `http` connections but will accept `https` connections, assuming the other preconditions for `https` have been met.
I apologize for the lack of a unit test to accompany this change, but I'm not a web developer and wasn't really sure how to go about adding one!

Added option for --ssl-only noVNC session

---

core/rfb.js
tests/test.rfb.js

The RFB protocol specifies a max version of 3.8, but RealVNC likes to
increment their version when they add new features.  RealVNC 5.3 sends
"005.000" as the version string, since they've extended their
implementation upon RFB v3.8.  We can detect that, and just tell them we
only speak 3.8, instead of barfing on "005.000" as an invalid version.
Closes #585

Detect RealVNC's VNC 5.0 Protocol Version

---

app/ui.js
core/rfb.js
core/util.js
tests/test.rfb.js
vnc_auto.html

The user interface should not have to be concerned about the protocol state. This change allows for cleaner state logic and removes special corner cases.
Note that this change breaks dependencies for the RFB module since it no longer sends out updates regarding protocol state via onUpdateState. But this is partly by design to avoid spamming the user-interface with irrelevant state updates.

Separate visual state from protocol state

---

app/ui.js
core/input/devices.js
core/util.js
tests/input.html

This is necessary to detect touch emulation in chrome. Unless anyone knows of any problems with this, I will merge soon.

New way of detecting touch

---

app/images/error.svg
app/images/info.svg

Give them a solid background to make them more easily identifiable
as icons, rather than text or some other more inline element.
A bit of bike shedding, but I think this is a worthwhile improvement. You now get easily recognisable shapes for the messages: round for info, triangle for warning, square for error.

Improve info and error icons

---

core/input/devices.js

Mouse wheel event handling has now been standardised and has broad
support. Use this event rather than the older, non-standard ones.
At the same time fix up support for horisontal mouse wheel events.
Tested on Windows, Linux and macOS.

Support standard mouse wheel event

---

app/ui.js
core/input/keysymdef.js
core/input/util.js
core/rfb.js
tests/test.helper.js
utils/parse.js

We had a bug where we would send a Unicode codepoint as a keysym to the server. This of course ended up with a completely wrong symbol.
Also made sure we can transfer the entire Unicode range.

Don't send Unicode as keysym

---

app/ui.js
core/display.js
core/rfb.js
tests/assertions.js
tests/playback.js
tests/test.display.js
tests/test.rfb.js
tests/vnc_perf.html
tests/vnc_playback.html

Do all rendering to a hidden canvas and then copy over the finished frame to the visible canvas once everything is done. This simplifies things and solves some bugs as we can retain a copy of the entire
frame buffer.
Tested on Chrome and Firefox. Performance is roughly the same after these changes, so no gain there unfortunately. But it makes panning behave very nicely and it allows for more fun stuff with panning and zooming in the future.

Display double buffering

---

core/rfb.js

Regression caused by e549ae074fcea9febde32c0fa260a64c15cc1b8e. Things work fine with 84cd0e719ead6a1d99827d00794ef821593564fc. The function display.get_context() was removed but it is still called in rfb.js in _cleanup().
This results in bugs where you for example are be unable to write in text input fields after disconnecting.
@ossman removing this wasn't intended I guess?

Fix rfb._cleanup()

---

app/ui.js
vnc.html

Instead of saving settings when clicking on apply or toggling the settings panel, save them immediately after a change. This is more in line with how most modern interfaces work and saves us from having two different 'states' to keep track of in the UI code (cookie and HTML-elem value).

Save settings immediately

---

include/util.js

This change will preserve file and line number reporting when Util.[Debug|Info|Warn|Error] is called, which should make development and debugging a lot easier.
See http://stackoverflow.com/questions/13815640/a-proper-wrapper-for-console-log-with-correct-line-number for an explanation of the binding.

Map Util.[Debug|Info|Warn|Error] to console.[debug|info|warn|error].

---

core/rfb.js

The old default was to ask for the maximum compression level. This
is against the recommendations in libvncserver/tight.c due to excessive
CPU load. It also causes Vino 3.8.1 (still shipped with Ubuntu 16.04
LTS) to prefer the blurry JPEG compression too much - e.g. red text on
the default background in MATE terminal becomes almost unreadable.
The new default is the recommended compression level for low-color
workloads, according to libvncserver source. Also, it is the maximum
compression level that doesn't trigger the Vino bug with red text in
most cases.
Fixes issue #737.

Changed the default compression level to 2

---

vnc_auto.html

Commit fa5b334dcbe7a5dab21580b54cc2f5f142600379 by Joel Martin changed
getQueryVal() to always decode the value using decodeURIComponent(), but
unescape() is still used for extracting the title, leading to
double-unescaping.
As unescape() is deprecated anyway, remove the last user.
Cc: Joel Martin <github@martintribe.org>
Cc: Anthony Young <sleepsonthefloor@gmail.com>

Remove double unescaping of title

---

package.json

It's spelled "MPL-2.0" according to https://spdx.org/licenses/.
This is important for license scanners as cockpit's (this came up in https://github.com/cockpit-project/cockpit/pull/5932).

Fix license name in package.json

---

app/styles/base.css
app/ui.js
vnc.html

The control bar can be dragged to the other side, this isn't obvious however. This adds a hint on the opposite side in the form of a subtle glowing half-ellipse. The hint appears when you press and hold the control bar handle.
I had another proposal in PR #732 which I scrapped mostly due to the added complexity. I believe with this approach it is easier to understand the hint, and it's much cleaner code.

Add hint that the control bar can be moved

---

core/rfb.js
tests/test.rfb.js

Supports server configurations that might prefer wss:// connections
on the default port, then proxies them through the web server to the
VNC server.
This proxy configuration is helpful on servers using self-signed
certificates.  Accessing the https://<host>/vnc_auto.html page and
adding an exception for that host is sufficient to also satisfy the
wss://<host>/ request, unlike requests to wss://<host>:<port>/ which
may require an extra exception.

rfb: Allow port to be optionally appended to URI

---

vnc_lite.html

Safari and Chrome now have native support for modules, so we need to make sure we only load our polyfill when actually needed.

Only load ES6 module loader polyfill if needed

---

core/encodings.js
core/rfb.js
core/websock.js
tests/test.rfb.js
tests/test.websock.js

This restores basic support for Intel AMT servers. They refuse clients that request more than 16 bits per pixels, so implement a fallback in just the "Raw" encoding.

Basic support for Intel AMT

---

app/styles/base.css
app/styles/lite.css
app/ui.js
core/display.js
core/rfb.js
docs/API-internal.md
docs/API.md
tests/test.display.js
tests/test.rfb.js
vnc.html
vnc_lite.html

Makes the API simpler and makes it easier for other frontends to get this functionality. Just look at the diff for `ui.js`. And the second commit demonstrates how easy it is for other frontends to start using these features. :)
This is the final portion I want in for #924.

Move resize handling in to RFB object

---

core/display.js

Without this, noVNC will display a blank screen when dealing with a server that sends 16 by 16 tiles.

Initalize cached 16x16 tile.

---

app/ui.js

I found an issue where the view_only parameter in the url was not respected during automatic connection.
To reproduce, open an url similar to this: .../noVNC/vnc.html?host=...&autoconnect=1&view_only=true&resize=none
After successful connection, the checkbox in the UI on the left side is checked for "
View only", but it is not respected. If I uncheck it and check it again, it is respected.
The following change fixes the bug, although I am not very familiar with the codebase, so this might not be the best solution.

Fix view_only setting with autoconnect

---

tests/test.display.js

IE11 doesn't support the `slice` method on ArrayBufferViews, so
we have to use the old `Array.prototype.slice.call` trick in the
tests instead.

Fix slice usage in display tests on IE11

---

app/ui.js
app/webutil.js
karma.conf.js
tests/test.webutil.js

This makes query overrides temporary (i.e. they do not change the value, if any, in local storage).  I believe it also solves #799.

Use localstorage only to initialize settings map

---

core/input/keyboard.js
tests/test.keyboard.js

Try to properly detect the fake CtrlL+AltR sequence Windows sends when pressing AltGr. This allows us to send more accurate key events over to the server.
This mainly makes things better when using QEMU key events, but other cases will improve as well.
The remaining corner case is Ctrl+AltGr which only works if the browser has special handling for it (only Chrome so far). On most browsers we'll get Ctrl+Alt instead. But before this patch we got nothing at all, so it is not necessarily worse.
Based on the same work in TigerVNC:
https://github.com/TigerVNC/tigervnc/commit/5124978b10641ca25607480f3bfbe9c29b5b6cc4

Better detection of AltGr on Windows

---

core/input/keyboard.js
core/util/browser.js

Firefox no longer sends keyup events properly for the Alt keys. Try to sniff out the state of the Alt key by monitoring other events that include its state.
Relevant Firefox bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1335347
https://bugzilla.mozilla.org/show_bug.cgi?id=1435717

Work around broken Alt keyup in Firefox

---

.travis.yml

We want to also test Microsoft Edge, and Internet Explorer on Windows 10
is really a reskinned Edge so we also need to test on Windows 7.

Update browser test list

---

core/rfb.js
tests/test.rfb.js

Pasting clipboard texts that were larger than 10240 bytes didnt work and caused a crash in noVNC. This commit fixes the crash and adds handling for sending large clipboard texts. Fixes issue #1065.

Handle sending large clipboards

---

utils/launch.sh

Fixes #1075 
Small issue but if you're going to do something you might as well avoid using deprecated tools :do_not_litter: 
Rather than trying to pick a utility, we should be able to just use bash to check if a port is available or not.
We can probably assume bash is available due to the shebang declaring it.
I've tested this on Red Hat 7, Fedora 27, Ubuntu 16.04 and Debian 9 with the version of bash from the default repos.
I can't test this on a mac, so someone might want to double check that.

Fixes #1075 by removing dependencies on external tools

---

core/display.js
core/rfb.js
core/util/cursor.js
docs/API-internal.md

Render the cursor on top of the canvas when we cannot rely on the browser to handle the cursor. This means that local cursor can now be used for touch devices and on IE/Edge.
Fixes #572.

Render cursor manually when needed

---

app/ui.js

If viewport drag was active when turning on scaling it wasn't disabled. Since drag isn't allowed (or useful) when scaling, we have to remember to disable it. Fixes #1110.
Also did some code cleanup.

Turn off view drag when scaling

---

tests/playback.js
tests/vnc_playback.html
utils/launch.sh

This fixes playback.js, which got broken somewhere along the way during the refactors.  It also adds the ability to pass `--record` through `utils/launch.sh` to websockify, for easier recording for test purposes.

Fix test playback

---

core/display.js
core/rfb.js
tests/test.mouse.js

With high DPI systems we can end up with a container with a size that
is not an integer number of CSS pixels. Make sure we can handle those
cases by allowing a fractional size for the output canvas. Framebuffer
size and viewport coordinates are still restricted to integer dimensions
though.
Based on initial patch by Alexander E. Patrakov.
Fixes #1111.
More testing is needed. I don't have access to a full set of browsers right now.

Handle fractional screen sizes

---

core/decoders/copyrect.js
core/decoders/hextile.js
core/decoders/raw.js
core/decoders/rre.js
core/decoders/tight.js
core/decoders/tightpng.js
core/rfb.js

Makes things a lot clearer by letting each encoding handle its own details and state.
I've just done the initial shuffle and basic tests right now. Need to do some profiling as well, and an attempt at handling alpha cursors (which requires this change).
If anyone can test TightPNG, then that would be helpful. @DirectXMan12?

Move decoders to separate classes

---

core/decoders/hextile.js
core/decoders/tight.js
core/decoders/tightpng.js
core/rfb.js

It's not too relevant since both should work the same according to the spec. However, I think that's good to be consistent.

Use `new` when constructing errors

---

core/rfb.js
tests/fake.websocket.js
tests/test.rfb.js

We had some issues where the code would do bad things if data was split up over several WebSocket messages. This PR makes sure that scenario is tested, and fixes the broken cases the tests exposed.
Fixes #1195.

Fix bugs related to slow incoming data

---

app/ui.js
app/webutil.js
core/base64.js
core/des.js
core/display.js
core/input/mouse.js
core/rfb.js
core/util/browser.js
core/util/cursor.js
core/util/eventtarget.js
tests/test.webutil.js

I was looking at some stuff in the code base and here are few small improvements:
* Remove intermediate variable from mouse: so it's the same as in keyboard, consistency)
* Simplify keysymdef fallback
* Remove unnecessary constructor parameter from Cursor
* Remove unnecessary context from eventtarget: Since it uses an fat arrow function, it's prebound and the explicit context has no effect.
* Use default argument for base64: so it's more concise and readable. We discussed in a previous PR that default arguments are OK.
* Convert DES into a class: It was weird to have a function with a bunch of nested functions that returns an object and it's called with `new`. Now it looks simpler to me. Also extracted the static data out of it so it doesn't create a new copy on every instantiation. 
* …

Small improvements

---

app/ui.js

The request for this feature comes from making a page consisting of several `<iframe>`s, each with a noVNC viewer inside it.
In this setup, the fullscreen buttons do not work as expected, they just do nothing. 
This is because the `ui.js` implementation of `toggleFullscreen()` has no awareness for the fullscreen window actually being the parent window of the viewer.
Making the fullscreen buttons work is actually quite straightforward, except for the identification of the correct `<iframe>` in the parent window.
To solve the problem, I read a request variable, `iframeid`, and use that to select the correct element to put into fullscreen mode.
Testing the feature:
- build a simple page containing a viewer in an `<iframe>`,
- give the iframe an arbitrary `id` attribute,
- pass that value to …

Fullscreen from iframe

---

app/ui.js

Reverts novnc/noVNC#1236, since fullscreen can be enabled on iframes by adding the allowfullscreen attribute.

Revert "Fullscreen from iframe"

---

utils/launch.sh

Previously launch.sh would check both for the existence of a local
websockify file and websockify/run file.
This initial check should really be for a local websockify directory
as in packaged environments a file could very well be the actual
executable leading to launch.sh incorrectly attempting to use a local
version of websockify.

launch.sh: Check for a local websockify directory

---

README.md
utils/use_require.js
vnc.html
vnc_lite.html

Very few browsers are left in the wild that supports modules but not "nomodule", so let's simplify our handling a bit.
See here:
https://caniuse.com/#search=nomodule
It's basically Safari 10 (on both iOS and macOS) that is the issue, and there seems to be few devices out there still using it.

Use "nomodule" instead of manual check

---

core/websock.js
tests/test.websock.js

Fix two inefficiencies in how and when we compact the websocket receive buffer.
In most browsers, the impact of this is negligible, but on a high-res monitor in IE11, these issues could freeze the buffer for over half a second when a large FBU is received.
With these changes, compactions effectively disappear from IE11's profiler graph.

Optimize receive buffer

---

app/ui.js
core/encodings.js
core/rfb.js
tests/test.rfb.js

Added support for dynamically changing desktop name. Resets to default name after disconnect.

Desktop name improvements

---

core/encodings.js
core/rfb.js
tests/test.rfb.js

Supports both classic cursor type and alpha cursor type. In classic mode the server can send 'inverted' pixels for the cursor, our code does not support this but handles these pixels as opaque black.
Both classic and alpha cursors can be tested by using a Windows XP virtual machine in VMware. If cursor shadows are enabled in XP you will get VMware alpha encoded cursors and if shadows are disabled you will get classic ones.
You will probably also have to enable VNC connections for your VMware guest in the settings.

Add support for VMware cursor encoding

---

core/util/cursor.js
core/util/events.js

Fixes issue #1300 where the cursor disappeared sometimes in IE, Edge, and Chrome.
We also managed to fix the IE cursor problem that was described in that issue.
All in all, these changes are quite complex, but the commit messages and the code comments should be enough.

Fix disappearing cursor

---

app/ui.js

We got a regression from 2afda54 and other commits that were made at the same time. The regression was that we could no longer use the keyboard directly after using the extra keys, you would have to click the canvas first. This PR fixes that and also adds a visual queue to the fact that the canvas got the focus by fading the controlbar after a click on any of the extra keys.

Fix so that you can use the keyboard after using the extra keys

---

core/input/keyboard.js
tests/test.keyboard.js

Caps Lock on iOS only triggers key release or key press events. When it's clicked it will only send keydown, and next time it will only send keyup and so on. It should send both a key press and a key release.
Also added missing macOS unit tests for this workaround.

Fix missing caps lock events on iOS

---

core/rfb.js

Checking password for undefined instead of falsy. That way an empty password string is allowed.

Fix for issue #1317

---

core/rfb.js

Add try catch to `decodeUTF8` function to solve #1326

Solution option to solve #1326 problem

---

app/ui.js
core/util/browser.js

Instead of always disabling scrollbars on iOS and Android, this PR adds dynamic detection for this.
The reason scrollbars were disabled on iOS and Android was that on these platforms the scrollbars were very thin and gets hidden when you don't use them. We can detect this by looking at the size of the scrollbars.
Verified on:
**iOS 13**
**Android 9**
**Chromebook**
**Fedora 31**
**macOS 10.15**
**Windows 10**

Dynamically detect scrollbar size

---

core/util/cursor.js

Fixes #1358 
I still think that a separate `connect` method to make `Rfb` instances reusable is the way to go.
But this is an improvement nevertheless.

Remove generated HTML by Cursor when it detaches

---

app/ui.js

This should address https://github.com/novnc/noVNC/issues/1355, where users get a 404 on `package.json` if noVNC is running in a directory and not at the root.

Correcting path to package.json for running at a path other than root.

---

core/decoders/tight.js
core/deflator.js
core/encodings.js
core/inflator.js
core/rfb.js
core/util/int.js
tests/test.deflator.js
tests/test.int.js
tests/test.rfb.js
vendor/pako/lib/zlib/deflate.js
vendor/pako/lib/zlib/inflate.js

The current clipboard did not support transferring  Unicode characters. This pull request adds support for extended clipboard pseudo-encoding on the client. The server must also support extended clipboard pseoudo-encoding for this solution to take effect. The servers I know of use this protocol is TigerVNC and UltraVNC.
Fixes #61

Add extended clipboard Pseudo-Encoding

---

core/rfb.js
tests/test.rfb.js

If too much text is copied in the session, String.fromCharCode.apply()
would crash in Safari on macOS and Chrome on Linux. This commit fixes
this issue by avoiding apply() altogether. Also added test to cover this
issue.
Tested on:
| | Windows 10 | macOS 10.15 | Linux (Fedora 31)
| ------------- | ------------- |------------- |------------- |
| **Chrome 80**  | ✓  |✓  |✓  |
| **Firefox \***  | ✓ v.73  |✓ v.71  |✓ v.73  |
| **Safari 13**  | -  |-  |✓  |
| **Edge 44**  |✓  |-  |-  |
| **IE 11** |✓  |-  |-  |

Fix crash with too large clipboard data

---

app/ui.js

The clipboard side bar button serves no purpose if user uses 'View Only' mode. This commit hides this button in those instances.
Tested on Fedora 31 in Firefox 73 and Chrome 80.
Fixes #1368

Hide clipboard side bar button when view only mode

---

core/rfb.js
core/util/polyfill.js
docs/API.md
tests/test.rfb.js

This PR adds possibility to change the quality (aka [JPEG Quality Level Pseudo-encoding](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#jpeg-quality-level-pseudo-encoding)) on the fly. Previously, the value was hardcoded to be `6` (more precisely: `-32 + 6 = -26`).
`RFB` class got a new property `qualityLevel` which can be set immediately after the `RFB` constructor (and then encodings are sent once as part of `ServerInitialisation` state). But it can also be set in `connected` state (and then encodings are sent again).
Values passed to `qualityLevel` setter are strictly verified to be integers in range `[0, 9]`. Hence, for IE11, I have added `Number.isInteger()` polyfill.
This has only been tested against (latest) TigerVNC.
Partially resolves #396, #1150, #1288 and …

Add possibility to set quality ("JPEG Quality Level Pseudo-encoding")

---

app/ui.js

Closing the toolbar would make the focus remain on the toolbar and
not in the session. The only way to switch focus was to click in the
session. This commit will automatically switch back focus to the session
after closing the toolbar.
Tested on:
|| __Windows 10__ | __Windows 10 touch__ | __Linux__ |
|-|-------------|------------|------------|
|Chrome v.80|  ✓|   ✓   |  ✓   |✓|
|Firefox|    ✓ v.74 |   ✓v.73   |✓v.73| 
|IE11|            ✓| ✓ | -  |
|Edge v.44|      ✓ | ✓ | -   |

Fix focus problem after closing the toolbar

---

docs/API.md

Thank you very much for your efforts developing noVNC, they are very much appreciated. noVNC is the central tool I used to build [Agdapad](https://agdapad.quasicoherent.io/).
This pull request updates the API documentation to include the default setting of `focusOnClick`.

Document default setting of `focusOnClick`

---

.eslintrc
app/ui.js
app/webutil.js
core/base64.js
core/decoders/hextile.js
core/decoders/raw.js
core/deflator.js
core/display.js
core/inflator.js
core/rfb.js
core/util/logging.js
core/websock.js
tests/assertions.js
tests/fake.websocket.js
tests/playback-ui.js
tests/playback.js
tests/test.deflator.js
tests/test.display.js
tests/test.rfb.js
tests/test.util.js
tests/test.websock.js
utils/genkeysymdef.js
utils/use_require.js
utils/use_require_helpers.js

Most of our code is written with camelCase naming. Let's standardize on that and enforce it using our linter.

Enforce camelCase

---

utils/launch.sh

Adding these options to `launch.sh` so I can quickly set them for my heavy use noVNC instance.

Make timeouts/heartbeats easy to setup

---

core/rfb.js

Some people have longer passwords than 256 characters (hooray for
password managers!). Server implementations also allow longer passwords:
TigerVNC allows up to 1024 characters.

Allow longer passwords in Plain authentication

---

core/rfb.js
core/websock.js
docs/API.md
tests/fake.websocket.js
tests/test.websock.js

This work is originally by Ryan Castner <castner.rr@gmail.com> and submitted as a PR here https://github.com/novnc/noVNC/pull/1362
Architecturally it is much the same except it doesn't rename a lot of variables to make this more reviewable. It also avoids unrelated changes such as replacing .onclose with an event listener, which caused numerous test failures.
It also adds in ppoffice's fix to initialise the buffers.
Like the original author I don't have enough time available to refactor this project to the new style event listeners.

Added support for RTCDataChannel

---

core/rfb.js

Most places that check for the presence / absence of credentials compare
them against `undefined`, except the one for Plain authentication.
This change makes the very last place to use the same pattern (instead
of checking for falsiness) for consistency. Additionally, there are ways
to configure PAM to accept empty passwords, so it's possible for a user
to legitimately send an empty string as password.

Normalize the credentials presence check

---

core/rfb.js
tests/test.rfb.js

This change adds tests for the VeNCrypt Plain authentication. In doing
that, this also fixes a typo that was introduced in a recent change.

Add VeNCrypt Plain authentication tests

---

core/rfb.js
docs/API.md

This is an error that presents itself with RTCDataChannel's, I suspect this could not
happen with a pre-existing WebSocket.
If the remote connection creates a data channel then the local (VNC) side gets a channel
created callback. It may also be the case that in that very same tick the socket is also
opened and buffered data received. This meant that (in my tests) about 1/3 of the time
noVNC would fail to respond to the initial message from the server because it was received
and subsequently not handled during that initial tick.
I'm not sure if this is the correct way to fix this. It is the only way I could see short of changing the noVNC flow to construct, attach listeners, then call a new open() method with the url or channel.

Fixed a race condition when attaching to an existing socket

---

core/rfb.js
core/websock.js
tests/test.rfb.js
tests/test.websock.js

New attempt at #1537. Instead of bypassing `setTimeout()` when using an existing object, we instead get rid of the reason for that timeout.
@TimSBSquare , could you test this? I don't have any setup here that uses existing objects.

Fix connection race with existing WebSocket/RTCDatachannel

---

README.md
core/rfb.js
tests/test.rfb.js

Fixes an issue where if the screen div resizes for a reason other than window resize, the canvas wouldn't redraw.
https://github.com/novnc/noVNC/issues/1364

feature: Detect parent resize

---

vnc.html

These are used via CSS, which means the browser doesn't load them until
an element actually gets those CSS rules. There can be some delay to
this loading which causes visual glitches. By preloading we can make
sure those images are cached and ready when the status bar appears.

Preload status bar images

---

.github/workflows/deploy.yml
snap/snapcraft.yaml

You can't include dependencies if you use the "stage:" or "prime:" filters as they will also filter the files from your dependencies. This is apparently per design and not a bug...
Fixes #1598.

Move snap dependencies to separate parts

---

vnc.html

"Fullscreen", or more correctly "Full-screen", refers to the
adjective. In this case, we want the tooltip of the full-screen button to
refer to the noun "Full Screen" as this seems to be the convention.
See:
https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/f/full-screen
https://english.stackexchange.com/questions/162421/fullscreen-or-full-screen
https://ell.stackexchange.com/questions/157952/full-screen-full-screen-or-fullscreen

Use "Full Screen" instead of "Fullscreen"

---

README.md

Not desirable to bind to public Internet unless necessary, especially for unprotected VNC.

Document binding to localhost in Quick Start

---

core/rfb.js
tests/test.rfb.js

Also includes some minor fixups of the unit tests and the removal of an old unnecessary workaround for buggy scrollbars in Google Chrome.
Closes #1616

Fix issue with ResizeObservers and scrollbars

---

app/ui.js

Currently novnc will only retry once (assuming the server is unavailable) and then stop (as the detail from is unclean, usually "failed to connect"). Minor change will continue to reconnect every reconnect_delay seconds until either reconnected or user intervention cancels the attempt.
Enhancement to #747

Allow continued reconnect tries

---

core/input/keyboard.js
tests/test.keyboard.js

Fixes #1695 by auto releasing keys while meta is held down, similar as [apache guacamole's solution](https://github.com/apache/guacamole-client/blob/165bd413c0ab9c55b0c0e3614fcb829ef5f8ca95/guacamole-common-js/src/main/webapp/modules/Keyboard.js#L286-L289).
Must be merged after #1697 or editted based on the outcme of #1696.

MacOS meta key (⌘) with a different key has unreliable keyup event

---

core/rfb.js
tests/assertions.js
tests/test.rfb.js

Add a more explicit '?' for characters that the clipboard cannot handle, instead of getting random junk.

Mask unsupported clipboard characters

---

app/styles/base.css
app/styles/input.css
app/ui.js
vnc.html

Here's some more CSS cleanup. Many parts of the code were relying on the class `root.noVNC_touch`, which was set by the JavaScript. Firstly, this dependency isn't ideal, and secondly, it made many CSS selectors very complex.
Instead, we can use `@media (any-pointer: coarse)` to detect if there is a coarse (not accurate) pointing device available. This basically translates to; if there is a touch screen available. Our testing shows that this method is comparable.
Moreover, here's a 3rd party source where testing results for this media query can be found:
https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/results/
Note that this approach still isn't perfect. For example, on Linux, even if a touch screen is plugged in, we still get `False` on `any-pointer: coarse`. …

Replace JavaScript .noVNC_touch with CSS @media (any-pointer: coarse)

---

core/crypto/aes.js
core/crypto/bigint.js
core/crypto/crypto.js
core/crypto/des.js
core/crypto/dh.js
core/crypto/md5.js
core/crypto/rsa.js
core/ra2.js
core/rfb.js
tests/test.rfb.js

noVNC has introduced many cryptographic algorithms including AES, DES, SHA1, MD5 and RSA for multiple security types. However, the code for these algorithms are distributed in different files. Also, some code, such as the one for the conversion between BigInt and Uint8Array, modPow and AES block cipher with AES-CBC, is duplicated. This PR does the following things with two commits:
The first commit 1. puts all code for cryptographic algorithms to a new directory `core/crypto` ; 2. adds wrappers for the algorithms including SHA1, AES and RSA keygen to prevent directly using the SubtleCrypto API.
The second commit adds the fallback implementations for AES, SHA1 and RSA keygen when SubtleCrypto is not available, which is the case for insecure contexts. With these changes, RSA-AES, ARD should …

Cleanup for cryptographic algorithms

---

app/ui.js

Adds "en" to the list of supported languages so that it can at least get picked up as a language in that "Second Pass: fallback" when translating. 
This is so that it doesn't ignore english in cases where a browser doesn't have "English" or "English-US" as their set language, but have something like "English-Canada" or "English-UK" as their primary language set in their browser.

Add english to list of supported languages

---

app/webutil.js
tests/test.webutil.js

Our settings are not a fatal requirement, we can fall back on the default values if they can't be accessed. A scenario where we've seen this happen is when cookies are disabled in the browser. It seems `localStorage` is disabled along with cookies in these settings.
Fixes issue #1577.

Don't crash if we can't use localStorage

---

core/encodings.js
core/input/keyboard.js
core/rfb.js
tests/test.keyboard.js
tests/test.rfb.js

QEMU supports using a Pseudo Encoding to send keyboard LED status to the VNC client:
https://www.qemu.org/docs/master/interop/vnc-ledstate-pseudo-encoding.html
This complements the QEMU extended key event no-vnc already supports. When you have a VNC server like QEMU that uses the extended key events to send the scan codes of the pressed keys, instead of the letter that is typed, the remote state of the keyboards CapsLock, NumLock and ScrollLock matters, instead of the local state.
This pull request just exposes these events, if supported by the VNC server, via an event. This way, it is possible for an integrator of no-vnc to show the remote keyboard led states in the client.

Add support for QEMU LED State pseudo encoding

---

docs/novnc_proxy.1
utils/novnc_proxy

For instance, for listening only on "localhost"
That is, bind on 127.0.0.1 instead of 0.0.0.0
Closes #1798

Add the possibility to listen on a specific host

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/translate.yml
utils/convert.js

Primarily to avoid the versions that are now deprecated, but also update actions/upload-artifact to keep us up to date.

Update github actions to latest versions

---

core/util/cursor.js

Hi,
we were getting a `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node` from this call because the cursor had already been removed from the DOM.
This happens in our case because we use noVNC together with [Turbo](https://turbo.hotwired.dev/handbook/introduction). This is a library / framework that replaces parts of the page or the entire document with server side rendered content.
So when leaving the page with the connected noVNC on it, we need to call `rfb.disconnect()` to close the connection, since we remain in the same JS context. By the time we do that, the DOM is already replaced though, so the canvas is no longer in `document` and the error occurs.
Since this line in noVNC is intended to remove the element from the DOM, …

Avoid exception when cursor was removed from DOM already

---

README.md
core/decoders/zlib.js
core/encodings.js
core/rfb.js
tests/test.zlib.js

The FreeBSD hypervisor (bhyve) has a built-in VNC server supporting both Raw and Zlib. Adding Zlib encoding to noVNC will reduce the data transferred between the server and client. And will add this encoding for other use cases as well.

Add Zlib encoding

---

core/decoders/h264.js
core/display.js
core/encodings.js
core/rfb.js
core/util/browser.js
tests/test.h264.js

This adds the Open H.264 encoding to noVNC, as defined here: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#open-h-264-encoding
This was tested on the following browsers:
* Firefox 127.0.2  with `dom.media.webcodecs.enabled=true`
* Firefox Nightly 129.0a1 (2024-07-08)
* Chromium 126.0.6478.126
I haven't run into any issues with Chromium, but Firefox keeps killing the decoder after a few frames because it thinks that the hardware decoder is too slow, so it wants to switch to software. However, after the switch, a new key frame is needed, so the decoder goes into a bad state and a reconfiguration is required, so this sequence of events is repeated indefinitely.
We can work around Firefox's issue by setting a frame duration for each frame, but that would be a hack. We don't …

WebCodecs H.264

---

core/rfb.js
tests/test.rfb.js

Instead of keeping track of button states ourselves by looking at `MouseEvent.button`, we can use the `MouseEvent.buttons` which already contains the state of all buttons.
Note that in `MouseEvent.button`,  button numbers are mapped as follows:
```
0 -> Left
1 -> Middle
2 -> Right
3 -> Back
4 -> Forward
```
But when looking at the `MouseEvent.buttons` property, the bits middle and right are switched, which is confusing:
```
0 -> Left
1 -> Right
2 -> Middle
3 -> Back
4 -> Forward
```
With this change, #1919 could be modified to work with Safari as well.
Unfortunately, the internal `_mouseButtonStateMask` state is not removed in this PR as it would require a large rewrite of the general architecture.
Tested on:
* Linux
* Firefox
* Chrome
* Epiphany
* Windows 11
* Edge
* Chrome
* Firefox
* …

Use MouseEvent.buttons for button state tracking

---

core/encodings.js
core/rfb.js
tests/test.rfb.js

This commit implements the extendedMouseButtons pseudo-encoding, which makes it possible to use the forward and back mouse buttons.
It looks like chromium is the only browser that has support for this currently.  See #1918 for more info.
Confirmed that it works with chromium on Mac, Linux and Windows against TigerVNC server.

Add support for forward and back mouse buttons

---

vnc.html

It is good practice to provide styling that help indicate the importance of the presented text.

Use semantic tags instead of style tags

---

app/styles/base.css
app/styles/constants.css
app/styles/input.css
utils/validate
vnc.html

This PR mainly includes a refreshed input.css:
* No more gradients
* Larger input elements
* Clear visual difference between buttons and text inputs
* New styles for indicating pressed state (:active)
But also a few changes to base.css & vnc.html:
* More spacing between elements
* Toggle switches instead of checkboxes in settings

Slight UI refresh

---

core/rfb.js
tests/test.rfb.js

Be more aggressive with resizing, limiting it to once ever 100 ms instead of after a 500 ms idle period. This gives a more responsive user experience.
Basically, https://github.com/TigerVNC/tigervnc/pull/1904 for noVNC.

Better resize rate limiting 

---

app/ui.js

Apparently there is some magic happening under the surface when the `path`-string containing a search query is assigned to `url.pathname`.
This is what caused `?` to be translated to `%3F`.

Let browser handle parsing of urls before relaying

---

core/rfb.js

This has been deprecated for around six years now. Let's remove the deprecation warning and disable setting `showDotCursor` via the options-parameter.

Disable setting showDotCursor in RFB constructor
