novnc/noVNC

include/display.js
include/ui.js
include/util.js
tests/test.display.js
vnc.html

This commit adds support for local autoscaling (both upscaling and downscaling, with the option to disable upscaling), based on #117.
Closes #117.
Credit goes to @mightypenguin for his initial work in #117 -- this is just an updated version of that with UI improvements.

Introduce Local Autoscaling

---

vnc_auto.html

Fixed incorrect UI usage and minor updateState params errors in vnc_auto.html

---

include/webutil.js

Missed a line and therefore the closing bracket on PR #597.

Adds missed line from PR 597

---

include/display.js

No test - sorry! However, you can probably create one from debug.5.js.zip in the ticket.

Fixed RGB data buffer size (issue 615)

---

include/rfb.js
tests/assertions.js
tests/test.rfb.js

Continuous Updates and Fence
--------------------------------
Continuous updates in the context of VNC means that, instead of waiting for the client to request frame buffer updates, the server will keep sending updates continuously.
The two extensions called "Fence" and "Continuous Updates" are needed for this and are implemented in this PR, as described in the RFB protocol available here:
https://github.com/rfbproto/rfbproto
While the continuous update functionality itself doesn't strictly require fencing, without it, buffer limits on the network could easily be hit. This is where fencing comes in, it is a flow-control mechanism. The server will use the fencing messages to determine how often it will send updates.
If Continuous Updates isn't supported by the server, noVNC will fall back …

Continuous Updates

---

app/ui.js
core/rfb.js

This PR fixes a number of issues with view-only:
* Keyboard and mouse were grabbed even in view-only (#644)
* A view-only session could change the desktop size
* The UI modified the keyboard and the mouse in view-only

Fix view only

---

app/locale/locale-de-DE.js
app/locale/locale-en-GB.js
app/locale/locale-nl-NL.js
app/ui.js
core/util.js

I created localization in German, Dutch and English for the messages in
the top messagebar and some logs.
I've used full English strings for lookup.
This is the new version of PR #548, because I made a few mistakes.

Localization support added for messages

---

app/locale/locale-el-GR.js
core/util.js

I added the Greek locale for the messages appearing in the statusbar. 
I hope it is ok.

Added Greek translation

---

app/ui.js

This prevents the focus being lost rather than trying to restore it
at various places.
Tested on the major browsers on iOS and Android.

Better method to keep focus on virtual keyboard

---

app/locale/locale-de-DE.js
app/locale/locale-el-GR.js
app/locale/locale-en-GB.js
app/locale/locale-nl-NL.js
app/locale/locale-sv-SE.js
app/styles/base.css
app/ui.js
vnc.html

Provides better feedback when connecting or disconnecting.

Blocking transition screen when connecting/disconnecting

---

app/styles/base.css
app/ui.js
core/rfb.js
tests/test.rfb.js
vnc.html

Adds a catch fallback for uncaught errors as well as changing the way RFB._fail() works. This fixes #678 as well.

Better error handling

---

app/images/handle_bg.svg
app/styles/base.css
app/ui.js

In case the remote session has something on the left side that makes the control bar's placement there inconvenient.

Allow control bar to be moved to the right side

---

app/styles/base.css
app/ui.js
vnc.html

Add an option to automatically reconnect after a delay when the
connection is closed.
Closes #746

Add reconnect option

---

app/ui.js
core/rfb.js

The settings for clip, view_only, reconnect, reconnect_delay, and local_cursor have no good reasons for not being changeable while connected. This PR enables the UI and puts some missing logical pieces into place.

Allow settings to be changed while connected

---

include/input.js

This PR backports @zarmhast's #619 fix into the [novnc/noVNC#stable/v0.6 branch](https://github.com/novnc/noVNC/tree/stable/v0.6).
No other changes have been made.

Backport #619 into stable/v0.6

---

core/display.js

The browsers' support for Microsoft's cursor format is a bit spotty,
so use the more common PNG format instead. This also allows us to
use a Canvas to generate the image, rather than coding it by hand.
Fixes #740.

Use PNG for mouse cursors

---

core/input/devices.js
core/input/xtscancodes.js
core/rfb.js
tests/test.keyboard.js

This fixes some more corner cases for the keyboard handling:
- Dead keys with QEMU
- iOS 9 compatibility
- Ctrl+key on IE and Edge (regression)

Various keyboard fixes

---

core/rfb.js

TypeScript error: novnc/core/rfb.js(1012,17): Error TS7027: Unreachable code detected.
I was able to import the ES modules into typescript OK apart from this line. It is right the line is unreachable.

fix typscript error - the only one.

---

.travis.yml

Travis-Sauce authentication somehow broke along the way.  This PR
fixes that by resetting the credentials.

[infra] Fix Travis Sauce Auth

---

app/webutil.js

Add missing quotes when checking against typeof

Add missing quotes

---

app/styles/lite.css
vnc_lite.html

Problems fixed:
* The canvas wasn't centered vertically (#881)
* The status text was previously only centered in the remaining space from the buttons
* There were conflicting styles in html and css

Properly center things in vnc_lite.html

---

README.md

This can help users find the content faster :)

Add README.md "Table of Contents" for readability

---

app/webutil.js
core/base64.js
core/input/keyboard.js

Remove console statements logs and replace them by `utils/logging.js`

Remove console statements

---

core/rfb.js
core/util/events.js

Remove unnecessary base64 dependency

---

app/ui.js
core/input/keyboard.js
core/input/mouse.js
core/input/util.js
core/rfb.js
core/util/browser.js
tests/test.helper.js
tests/test.keyboard.js

Just move all the duplicate `isMac`, `isWindow`, etc. to `browser.js`

Move browser checks to browser.js

---

core/encodings.js
core/rfb.js

Refer discussion on https://github.com/novnc/noVNC/issues/25, https://github.com/novnc/noVNC/issues/1023

add encoding support for TightPNG

---

utils/use_require.js
utils/use_require_helpers.js

Some improvements to our conversion script to make it more useful when converting the application:
- Fixes some races by using promises
- Cleans up unnecessary files when bundling (fixes #970)
- Lets converted modules be a fallback rather than forced on all browsers

improve use_require.js

---

app/ui.js
po/Makefile
po/zh_CN.po

Add translation in zh_CN.
Signed-off-by: CUI Wei <ghostplant@qq.com>

Add translation in zh_CN

---

.travis.yml
karma.conf.js

Makes sure we get early feedback for lint violations.
Also split up the tests more to avoid stability issues with Sauce.

Run eslint in travis

---

docs/EMBEDDING.md

This is a minimal documentation-only solution for issue #1097.

Document browser cache issue and add a workaround

---

app/ui.js
po/Makefile
po/cs.po

Czech translation

---

app/images/windows.svg
app/ui.js
vnc.html

Super key feature

---

core/rfb.js
docs/API.md

Add a pubic accessor to the screen style -> background property, so it can be customised from the client code if needed.
The previous discussion can be found at https://github.com/novnc/noVNC/pull/1189

Make the screen background customizable

---

vnc.html
vnc_lite.html

Fixes #1214 and other minor issues.

Some formatting fixes for HTML files

---

.travis.yml
tests/vnc_playback.html
utils/validate

Make sure they stay nice and clean when people change things.

Validate HTML and CSS in Travis

---

app/styles/base.css
app/ui.js
vnc.html

A second proposal for #1222.
An alternative to #1264.

Add version number to UI

---

core/rfb.js

This allows using TigerVNC server with PAM authentication (e.g. against
LDAP or other extensible authentication mechanisms)
Tested with TigerVNC server (Xvnc -SecurityTypes Plain -PlainUsers '*')
Should not break anything else, this method is tried last when all
other fail.
Tested in Firefox 74 and Chromium 80

rfb: VeNCrypt Plain SecurityType support

---

core/input/mouse.js

Limit mouse move events to one every 17 mS.

Limit mouse move events to one every 17 mS.

---

app/ui.js
core/rfb.js
docs/API.md
docs/EMBEDDING.md
tests/test.rfb.js
vnc.html

Like #1373 but for compression level.
Fixes issue #1382.

Add ability to set Tight compression level

---

po/ja.po

Sorry, I made a mistake in the comment.

Fix Japanese translation

---

utils/launch.sh

For debugging websockify with novnc it is handy if I can setup logging automatically.

Permit setting syslog on websockify

---

core/input/domkeytable.js

https://www.w3.org/TR/uievents-key/

chore: sync with W3C documentation

---

.github/workflows/deploy.yml
docs/EMBEDDING.md
docs/LIBRARY.md
snap/snapcraft.yaml

Missed some things in #1477. This also tweaks the snap building as it apparently was broken.

More cleanup after removal of Internet Explorer support

---

po/es.po

Update Spanish Translation.
Added missing translations. Fixed some typos.
Also, some changes were made to use a more formal and international spanish.

Update Spanish Translation

---

app/ui.js
po/Makefile
po/fr.po

feat: add French localization strings

---

.eslintrc
core/rfb.js
core/util/bigint-mod-arith.js
core/util/md5.js
tests/test.rfb.js

Added the support to perform authentication using the Apple Remote Desktop authentication protocol.  This required me to add the dependancy on the forge js encryption library for mobPow, MD5 and AES encryption.

Added support for Apple Remote Desktop authentication

---

core/rfb.js
tests/test.rfb.js

Overhaul of the security type handling, primarily to fix the ordering. It now follows what TigerVNC does, which is to respect the server order.
Also found some bugs along the way that got fixed.

Fix security type handling

---

utils/novnc_proxy

wanted to enable authentication in websockify but was unable to do so with the currently available params for the novnc script. These changes should add support for the required parameters.

add support for enabling authentication

---

core/display.js
core/rfb.js
docs/API.md

I would like to access the content of the framebuffer programatically. I have added two helper functions.
Adresses #209

Provide access to content of framebuffer

---

utils/novnc_proxy

expose --file-only option to disable dir listing
novnc_proxy optionally passes the flag to WEBSOCKIFY to disable dir listing
https://github.com/novnc/websockify/pull/536

expose websockify's --file-only option to disable dir listing

---

core/rfb.js

Set _rfbVeNCryptState = 4 not == 4

---

core/decoders/hextile.js
core/decoders/jpeg.js
core/decoders/raw.js
core/decoders/tight.js
core/decoders/zrle.js
core/display.js
core/ra2.js
core/rfb.js
core/websock.js
docs/API-internal.md
tests/fake.websocket.js
tests/playback.js
tests/test.display.js
tests/test.jpeg.js
tests/test.rfb.js
tests/test.tight.js
tests/test.tightpng.js
tests/test.websock.js

More clean-up as a result of playing around with async functions. Follow-up to #1780.

Websock API cleanup

---

core/decoders/tight.js

This commit is a basic implementation of the gradient filter required by qemu `lossy` option.
Tested on QEMU 8.2.2 and Firefox on Fedora 40.

Implement gradient filter of tight decoder, fixing issue #1767

---

README.md
core/util/browser.js
snap/local/svc_wrapper.sh

chore: fix some typos
